dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
branches:
  only:
    - main
    - next
node_js:
  - v14
  - v12
  - v10
env:
  - PLAYWRIGHT_OVERRIDE_VERSION=1.1.0
  - PLAYWRIGHT_OVERRIDE_VERSION=latest
before_install:
  - npm install -g yarn
before_script:
  - yarn add -D "playwright@${PLAYWRIGHT_OVERRIDE_VERSION}"
script:
  - yarn rebuild
  - yarn validate
after_success:
  - yarn ci-after-success

jobs:
  include:
    - stage: release
      node_js: 12
      env:
        - PLAYWRIGHT_OVERRIDE_VERSION=latest
      script: yarn ci-after-success
